### ISSUE TITLE
Error: File not found in demo.ipynb

### ISSUE THREAD

**Issue by vishwa702** [ruiqi-zhong/TestSuiteEval#2]
When running the notebook without making any changes to it, the cell that generates neighbor queries gives an error as described below. 

`FileNotFoundError                         Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_19740\2022686869.py in <module>
      1 from sql_util.run import exec_db_path
      2 print('original_database_path = ', original_database_path)
----> 3 gold_flag, gold_denotation = exec_db_path(original_database_path, gold_query)
      4 print('gold denotation')
      5 print(gold_denotation)

~\testsuite-Zhong\TestSuiteEval-main\sql_util\run.py in exec_db_path(sqlite_path, query, process_id, timeout)
     52             f_prefix = os.path.join(EXEC_TMP_DIR, process_id)
     53             print('f_prefix = ', f_prefix)
---> 54         pkl.dump((sqlite_path, query), open(f_prefix + '.in', 'wb'))
     55     try:
     56         subprocess.call(['python3', 'sql_util/exec_subprocess.py', f_prefix], timeout=timeout, stderr=open('runerr.log', 'a'))

**FileNotFoundError: [Errno 2] No such file or directory: 'tmp/1669260806.3811529316367483.in**'`

@CrafterKolyan @ruiqi-zhong Please provide a solution. Thanks!

**Comment by AkkIcon** [comment]
I fix it with  `makedir tmp`
